# You can find more information about RuboCop pending cops policy
# https://docs.rubocop.org/rubocop/versioning.html#pending-cops
#
# These are the default options. The .rubocop.yml inherit and
# override all the default options.
# https://github.com/rubocop-hq/rubocop/blob/master/config/default.yml
require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
AllCops:
  TargetRubyVersion: 2.7.3
  DisplayCopNames: true
  DisplayStyleGuide: true
  NewCops: enable

# Offense count: 1
# Configuration parameters: Include.
# Include: **/*.gemspec
Gemspec/RequiredRubyVersion:
  Exclude:
    - 'br_documents.gemspec'

# Offense count: 1
# Configuration parameters: Include.
# Include: **/*.gemspec
Gemspec/RubyVersionGlobalsUsage:
  Exclude:
    - 'br_documents.gemspec'

# Offense count: 1
# Configuration parameters: IgnoredMethods, CountRepeatedAttributes.
Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
   - 'spec/**/*.rb'

Style/Documentation:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false # default: true

RSpec/MultipleExpectations:
  Enabled: false # default: true

RSpec/NestedGroups:
  Enabled: false # default: true

Style/RegexpLiteral:
  Enabled: false # default: true

Style/FrozenStringLiteralComment:
  EnforcedStyle: never # default: always

# Offense count: 39
# Cop supports --auto-correct.
Style/RedundantRegexpEscape:
  Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: use_perl_names, use_english_names
Style/SpecialGlobalVars:
  Exclude:
    - 'br_documents.gemspec'

Style/WordArray:
  EnforcedStyle: brackets
